//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    /// Color `task_green`.
    static let task_green = Rswift.ColorResource(bundle: R.hostingBundle, name: "task_green")
    /// Color `task_red`.
    static let task_red = Rswift.ColorResource(bundle: R.hostingBundle, name: "task_red")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "task_green", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func task_green(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.task_green, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "task_red", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func task_red(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.task_red, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 20 images.
  struct image {
    /// Image `avatar`.
    static let avatar = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar")
    /// Image `cell_tower`.
    static let cell_tower = Rswift.ImageResource(bundle: R.hostingBundle, name: "cell_tower")
    /// Image `close_modal`.
    static let close_modal = Rswift.ImageResource(bundle: R.hostingBundle, name: "close_modal")
    /// Image `close`.
    static let close = Rswift.ImageResource(bundle: R.hostingBundle, name: "close")
    /// Image `done`.
    static let done = Rswift.ImageResource(bundle: R.hostingBundle, name: "done")
    /// Image `gps_filled`.
    static let gps_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "gps_filled")
    /// Image `gps`.
    static let gps = Rswift.ImageResource(bundle: R.hostingBundle, name: "gps")
    /// Image `logout`.
    static let logout = Rswift.ImageResource(bundle: R.hostingBundle, name: "logout")
    /// Image `map_filled`.
    static let map_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "map_filled")
    /// Image `map`.
    static let map = Rswift.ImageResource(bundle: R.hostingBundle, name: "map")
    /// Image `marker_filled`.
    static let marker_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "marker_filled")
    /// Image `marker`.
    static let marker = Rswift.ImageResource(bundle: R.hostingBundle, name: "marker")
    /// Image `refresh`.
    static let refresh = Rswift.ImageResource(bundle: R.hostingBundle, name: "refresh")
    /// Image `sites_filled`.
    static let sites_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "sites_filled")
    /// Image `sites`.
    static let sites = Rswift.ImageResource(bundle: R.hostingBundle, name: "sites")
    /// Image `sort`.
    static let sort = Rswift.ImageResource(bundle: R.hostingBundle, name: "sort")
    /// Image `tasks_filled`.
    static let tasks_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "tasks_filled")
    /// Image `tasks`.
    static let tasks = Rswift.ImageResource(bundle: R.hostingBundle, name: "tasks")
    /// Image `user_filled`.
    static let user_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "user_filled")
    /// Image `user`.
    static let user = Rswift.ImageResource(bundle: R.hostingBundle, name: "user")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "avatar", bundle: ..., traitCollection: ...)`
    static func avatar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "cell_tower", bundle: ..., traitCollection: ...)`
    static func cell_tower(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cell_tower, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "close", bundle: ..., traitCollection: ...)`
    static func close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "close_modal", bundle: ..., traitCollection: ...)`
    static func close_modal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close_modal, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "done", bundle: ..., traitCollection: ...)`
    static func done(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.done, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "gps", bundle: ..., traitCollection: ...)`
    static func gps(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gps, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "gps_filled", bundle: ..., traitCollection: ...)`
    static func gps_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gps_filled, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "logout", bundle: ..., traitCollection: ...)`
    static func logout(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logout, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "map", bundle: ..., traitCollection: ...)`
    static func map(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.map, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "map_filled", bundle: ..., traitCollection: ...)`
    static func map_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.map_filled, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "marker", bundle: ..., traitCollection: ...)`
    static func marker(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.marker, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "marker_filled", bundle: ..., traitCollection: ...)`
    static func marker_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.marker_filled, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "refresh", bundle: ..., traitCollection: ...)`
    static func refresh(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.refresh, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "sites", bundle: ..., traitCollection: ...)`
    static func sites(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sites, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "sites_filled", bundle: ..., traitCollection: ...)`
    static func sites_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sites_filled, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "sort", bundle: ..., traitCollection: ...)`
    static func sort(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sort, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "tasks", bundle: ..., traitCollection: ...)`
    static func tasks(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tasks, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "tasks_filled", bundle: ..., traitCollection: ...)`
    static func tasks_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tasks_filled, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "user", bundle: ..., traitCollection: ...)`
    static func user(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.user, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "user_filled", bundle: ..., traitCollection: ...)`
    static func user_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.user_filled, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 76 localization keys.
    struct localizable {
      /// en translation: %s km
      ///
      /// Locales: en, hr
      static let distance_in_km = Rswift.StringResource(key: "distance_in_km", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: %s m
      ///
      /// Locales: en, hr
      static let distance_in_m = Rswift.StringResource(key: "distance_in_m", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=check_if_user_exists&username='%s'&password='%s'
      ///
      /// Locales: en, hr
      static let check_if_user_exists = Rswift.StringResource(key: "check_if_user_exists", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_all_sites
      ///
      /// Locales: en, hr
      static let get_all_sites = Rswift.StringResource(key: "get_all_sites", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_all_users
      ///
      /// Locales: en, hr
      static let get_all_users = Rswift.StringResource(key: "get_all_users", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_site_status
      ///
      /// Locales: en, hr
      static let get_site_status = Rswift.StringResource(key: "get_site_status", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_task_status
      ///
      /// Locales: en, hr
      static let get_task_status = Rswift.StringResource(key: "get_task_status", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_tasks_for_user&user_id=%d
      ///
      /// Locales: en, hr
      static let get_tasks_for_user = Rswift.StringResource(key: "get_tasks_for_user", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: ?action=get_user_data&user_id=%d
      ///
      /// Locales: en, hr
      static let get_user_data = Rswift.StringResource(key: "get_user_data", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Address
      ///
      /// Locales: en, hr
      static let scope_address = Rswift.StringResource(key: "scope_address", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Address:
      ///
      /// Locales: en, hr
      static let site_address = Rswift.StringResource(key: "site_address", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: All
      ///
      /// Locales: en, hr
      static let all_tasks = Rswift.StringResource(key: "all_tasks", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: An error occurred while fetching data. %s
      ///
      /// Locales: en, hr
      static let error_alert_message = Rswift.StringResource(key: "error_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: An error occurred while updating data.
      ///
      /// Locales: en, hr
      static let post_error_alert_message = Rswift.StringResource(key: "post_error_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Ascending
      ///
      /// Locales: en, hr
      static let ascending = Rswift.StringResource(key: "ascending", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Cannot process data.
      ///
      /// Locales: en, hr
      static let cannot_process_data = Rswift.StringResource(key: "cannot_process_data", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Category:
      ///
      /// Locales: en, hr
      static let task_category = Rswift.StringResource(key: "task_category", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Closing time:
      ///
      /// Locales: en, hr
      static let task_closing_time = Rswift.StringResource(key: "task_closing_time", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Completed
      ///
      /// Locales: en, hr
      static let completed = Rswift.StringResource(key: "completed", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Date
      ///
      /// Locales: en, hr
      static let scope_date = Rswift.StringResource(key: "scope_date", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Descending
      ///
      /// Locales: en, hr
      static let descending = Rswift.StringResource(key: "descending", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Description:
      ///
      /// Locales: en, hr
      static let task_description = Rswift.StringResource(key: "task_description", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Directions:
      ///
      /// Locales: en, hr
      static let site_directions = Rswift.StringResource(key: "site_directions", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Distance
      ///
      /// Locales: en, hr
      static let distance = Rswift.StringResource(key: "distance", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Error
      ///
      /// Locales: en, hr
      static let error_alert_title = Rswift.StringResource(key: "error_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Fetching Data ...
      ///
      /// Locales: en, hr
      static let refresh_control_title = Rswift.StringResource(key: "refresh_control_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Location
      ///
      /// Locales: en, hr
      static let user_location = Rswift.StringResource(key: "user_location", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Location is denied
      ///
      /// Locales: en, hr
      static let location_denied_alert_title = Rswift.StringResource(key: "location_denied_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Location is restricted
      ///
      /// Locales: en, hr
      static let location_restricted_alert_title = Rswift.StringResource(key: "location_restricted_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Location is turned off
      ///
      /// Locales: en, hr
      static let location_off_alert_title = Rswift.StringResource(key: "location_off_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Location recorded:
      ///
      /// Locales: en, hr
      static let user_recorded = Rswift.StringResource(key: "user_recorded", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: LocationsUpdated
      ///
      /// Locales: en, hr
      static let notification_name = Rswift.StringResource(key: "notification_name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Login
      ///
      /// Locales: en, hr
      static let login = Rswift.StringResource(key: "login", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Login Failed
      ///
      /// Locales: en, hr
      static let failed_login_alert_title = Rswift.StringResource(key: "failed_login_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Map
      ///
      /// Locales: en, hr
      static let map = Rswift.StringResource(key: "map", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Mark
      ///
      /// Locales: en, hr
      static let scope_mark = Rswift.StringResource(key: "scope_mark", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Mark:
      ///
      /// Locales: en, hr
      static let site_mark = Rswift.StringResource(key: "site_mark", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Missing Fields
      ///
      /// Locales: en, hr
      static let missing_data_alert_title = Rswift.StringResource(key: "missing_data_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: My Location
      ///
      /// Locales: en, hr
      static let my_location = Rswift.StringResource(key: "my_location", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: My info
      ///
      /// Locales: en, hr
      static let my_info = Rswift.StringResource(key: "my_info", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Name
      ///
      /// Locales: en, hr
      static let scope_name = Rswift.StringResource(key: "scope_name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Name:
      ///
      /// Locales: en, hr
      static let site_name = Rswift.StringResource(key: "site_name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Name:
      ///
      /// Locales: en, hr
      static let user_name = Rswift.StringResource(key: "user_name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: No data available.
      ///
      /// Locales: en, hr
      static let no_data_available = Rswift.StringResource(key: "no_data_available", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: No internet connection.
      ///
      /// Locales: en, hr
      static let no_internet_connection = Rswift.StringResource(key: "no_internet_connection", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Not completed
      ///
      /// Locales: en, hr
      static let not_completed = Rswift.StringResource(key: "not_completed", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: OK
      ///
      /// Locales: en, hr
      static let alert_ok_action = Rswift.StringResource(key: "alert_ok_action", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Opening time:
      ///
      /// Locales: en, hr
      static let task_opening_time = Rswift.StringResource(key: "task_opening_time", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Password
      ///
      /// Locales: en, hr
      static let password = Rswift.StringResource(key: "password", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Please allow the app to use your location for all features to work.
      ///
      /// Locales: en, hr
      static let location_denied_alert_message = Rswift.StringResource(key: "location_denied_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Please enter your username and password.
      ///
      /// Locales: en, hr
      static let missing_data_alert_message = Rswift.StringResource(key: "missing_data_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Please turn on your location for all features to work.
      ///
      /// Locales: en, hr
      static let location_off_alert_message = Rswift.StringResource(key: "location_off_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Power supply:
      ///
      /// Locales: en, hr
      static let site_power = Rswift.StringResource(key: "site_power", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Search sites
      ///
      /// Locales: en, hr
      static let search_sites_placeholder = Rswift.StringResource(key: "search_sites_placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Site details
      ///
      /// Locales: en, hr
      static let site_details = Rswift.StringResource(key: "site_details", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Sites
      ///
      /// Locales: en, hr
      static let sites = Rswift.StringResource(key: "sites", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Sort
      ///
      /// Locales: en, hr
      static let sort = Rswift.StringResource(key: "sort", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Status:
      ///
      /// Locales: en, hr
      static let task_status = Rswift.StringResource(key: "task_status", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Task
      ///
      /// Locales: en, hr
      static let scope_task = Rswift.StringResource(key: "scope_task", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Task details
      ///
      /// Locales: en, hr
      static let task_details = Rswift.StringResource(key: "task_details", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Tasks
      ///
      /// Locales: en, hr
      static let tasks = Rswift.StringResource(key: "tasks", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Tech
      ///
      /// Locales: en, hr
      static let scope_tech = Rswift.StringResource(key: "scope_tech", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Technology:
      ///
      /// Locales: en, hr
      static let site_tech = Rswift.StringResource(key: "site_tech", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: The app is not authorized to use location services.
      ///
      /// Locales: en, hr
      static let location_restricted_alert_message = Rswift.StringResource(key: "location_restricted_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: The dequeued cell is not an instance of %s.
      ///
      /// Locales: en, hr
      static let cell_error = Rswift.StringResource(key: "cell_error", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: The username or password is incorrect.
      ///
      /// Locales: en, hr
      static let failed_login_alert_message = Rswift.StringResource(key: "failed_login_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: User
      ///
      /// Locales: en, hr
      static let user = Rswift.StringResource(key: "user", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Username
      ///
      /// Locales: en, hr
      static let username = Rswift.StringResource(key: "username", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Username:
      ///
      /// Locales: en, hr
      static let user_username = Rswift.StringResource(key: "user_username", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: Users
      ///
      /// Locales: en, hr
      static let users = Rswift.StringResource(key: "users", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: action_id=update_task_status&task_id=%d&recorded=%s
      ///
      /// Locales: en, hr
      static let update_task_status = Rswift.StringResource(key: "update_task_status", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: action_id=update_user_location&user_id=%d&lat=%f&lng=%f&recorded=%s
      ///
      /// Locales: en, hr
      static let update_user_location = Rswift.StringResource(key: "update_user_location", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: locations
      ///
      /// Locales: en, hr
      static let notification_info = Rswift.StringResource(key: "notification_info", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: loggedUser
      ///
      /// Locales: en, hr
      static let logged_user_key = Rswift.StringResource(key: "logged_user_key", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: siteSort
      ///
      /// Locales: en, hr
      static let site_sort_key = Rswift.StringResource(key: "site_sort_key", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)
      /// en translation: taskSort
      ///
      /// Locales: en, hr
      static let task_sort_key = Rswift.StringResource(key: "task_sort_key", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "hr"], comment: nil)

      /// en translation: %s km
      ///
      /// Locales: en, hr
      static func distance_in_km(_ value1: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("distance_in_km", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "distance_in_km"
        }

        let format = NSLocalizedString("distance_in_km", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: %s m
      ///
      /// Locales: en, hr
      static func distance_in_m(_ value1: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("distance_in_m", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "distance_in_m"
        }

        let format = NSLocalizedString("distance_in_m", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: ?action=check_if_user_exists&username='%s'&password='%s'
      ///
      /// Locales: en, hr
      static func check_if_user_exists(_ value1: UnsafePointer<CChar>, _ value2: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("check_if_user_exists", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "check_if_user_exists"
        }

        let format = NSLocalizedString("check_if_user_exists", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// en translation: ?action=get_all_sites
      ///
      /// Locales: en, hr
      static func get_all_sites(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("get_all_sites", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_all_sites"
        }

        return NSLocalizedString("get_all_sites", bundle: bundle, comment: "")
      }

      /// en translation: ?action=get_all_users
      ///
      /// Locales: en, hr
      static func get_all_users(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("get_all_users", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_all_users"
        }

        return NSLocalizedString("get_all_users", bundle: bundle, comment: "")
      }

      /// en translation: ?action=get_site_status
      ///
      /// Locales: en, hr
      static func get_site_status(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("get_site_status", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_site_status"
        }

        return NSLocalizedString("get_site_status", bundle: bundle, comment: "")
      }

      /// en translation: ?action=get_task_status
      ///
      /// Locales: en, hr
      static func get_task_status(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("get_task_status", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_task_status"
        }

        return NSLocalizedString("get_task_status", bundle: bundle, comment: "")
      }

      /// en translation: ?action=get_tasks_for_user&user_id=%d
      ///
      /// Locales: en, hr
      static func get_tasks_for_user(_ value1: Int, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("get_tasks_for_user", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_tasks_for_user"
        }

        let format = NSLocalizedString("get_tasks_for_user", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: ?action=get_user_data&user_id=%d
      ///
      /// Locales: en, hr
      static func get_user_data(_ value1: Int, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("get_user_data", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "get_user_data"
        }

        let format = NSLocalizedString("get_user_data", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: Address
      ///
      /// Locales: en, hr
      static func scope_address(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_address", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_address"
        }

        return NSLocalizedString("scope_address", bundle: bundle, comment: "")
      }

      /// en translation: Address:
      ///
      /// Locales: en, hr
      static func site_address(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_address", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_address"
        }

        return NSLocalizedString("site_address", bundle: bundle, comment: "")
      }

      /// en translation: All
      ///
      /// Locales: en, hr
      static func all_tasks(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("all_tasks", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "all_tasks"
        }

        return NSLocalizedString("all_tasks", bundle: bundle, comment: "")
      }

      /// en translation: An error occurred while fetching data. %s
      ///
      /// Locales: en, hr
      static func error_alert_message(_ value1: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("error_alert_message", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "error_alert_message"
        }

        let format = NSLocalizedString("error_alert_message", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: An error occurred while updating data.
      ///
      /// Locales: en, hr
      static func post_error_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("post_error_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "post_error_alert_message"
        }

        return NSLocalizedString("post_error_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: Ascending
      ///
      /// Locales: en, hr
      static func ascending(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ascending", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "ascending"
        }

        return NSLocalizedString("ascending", bundle: bundle, comment: "")
      }

      /// en translation: Cannot process data.
      ///
      /// Locales: en, hr
      static func cannot_process_data(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("cannot_process_data", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "cannot_process_data"
        }

        return NSLocalizedString("cannot_process_data", bundle: bundle, comment: "")
      }

      /// en translation: Category:
      ///
      /// Locales: en, hr
      static func task_category(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_category", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_category"
        }

        return NSLocalizedString("task_category", bundle: bundle, comment: "")
      }

      /// en translation: Closing time:
      ///
      /// Locales: en, hr
      static func task_closing_time(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_closing_time", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_closing_time"
        }

        return NSLocalizedString("task_closing_time", bundle: bundle, comment: "")
      }

      /// en translation: Completed
      ///
      /// Locales: en, hr
      static func completed(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("completed", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "completed"
        }

        return NSLocalizedString("completed", bundle: bundle, comment: "")
      }

      /// en translation: Date
      ///
      /// Locales: en, hr
      static func scope_date(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_date", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_date"
        }

        return NSLocalizedString("scope_date", bundle: bundle, comment: "")
      }

      /// en translation: Descending
      ///
      /// Locales: en, hr
      static func descending(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("descending", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "descending"
        }

        return NSLocalizedString("descending", bundle: bundle, comment: "")
      }

      /// en translation: Description:
      ///
      /// Locales: en, hr
      static func task_description(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_description", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_description"
        }

        return NSLocalizedString("task_description", bundle: bundle, comment: "")
      }

      /// en translation: Directions:
      ///
      /// Locales: en, hr
      static func site_directions(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_directions", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_directions"
        }

        return NSLocalizedString("site_directions", bundle: bundle, comment: "")
      }

      /// en translation: Distance
      ///
      /// Locales: en, hr
      static func distance(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("distance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "distance"
        }

        return NSLocalizedString("distance", bundle: bundle, comment: "")
      }

      /// en translation: Error
      ///
      /// Locales: en, hr
      static func error_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("error_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "error_alert_title"
        }

        return NSLocalizedString("error_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: Fetching Data ...
      ///
      /// Locales: en, hr
      static func refresh_control_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("refresh_control_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "refresh_control_title"
        }

        return NSLocalizedString("refresh_control_title", bundle: bundle, comment: "")
      }

      /// en translation: Location
      ///
      /// Locales: en, hr
      static func user_location(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("user_location", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "user_location"
        }

        return NSLocalizedString("user_location", bundle: bundle, comment: "")
      }

      /// en translation: Location is denied
      ///
      /// Locales: en, hr
      static func location_denied_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_denied_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_denied_alert_title"
        }

        return NSLocalizedString("location_denied_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: Location is restricted
      ///
      /// Locales: en, hr
      static func location_restricted_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_restricted_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_restricted_alert_title"
        }

        return NSLocalizedString("location_restricted_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: Location is turned off
      ///
      /// Locales: en, hr
      static func location_off_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_off_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_off_alert_title"
        }

        return NSLocalizedString("location_off_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: Location recorded:
      ///
      /// Locales: en, hr
      static func user_recorded(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("user_recorded", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "user_recorded"
        }

        return NSLocalizedString("user_recorded", bundle: bundle, comment: "")
      }

      /// en translation: LocationsUpdated
      ///
      /// Locales: en, hr
      static func notification_name(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("notification_name", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "notification_name"
        }

        return NSLocalizedString("notification_name", bundle: bundle, comment: "")
      }

      /// en translation: Login
      ///
      /// Locales: en, hr
      static func login(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("login", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "login"
        }

        return NSLocalizedString("login", bundle: bundle, comment: "")
      }

      /// en translation: Login Failed
      ///
      /// Locales: en, hr
      static func failed_login_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("failed_login_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "failed_login_alert_title"
        }

        return NSLocalizedString("failed_login_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: Map
      ///
      /// Locales: en, hr
      static func map(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("map", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "map"
        }

        return NSLocalizedString("map", bundle: bundle, comment: "")
      }

      /// en translation: Mark
      ///
      /// Locales: en, hr
      static func scope_mark(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_mark", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_mark"
        }

        return NSLocalizedString("scope_mark", bundle: bundle, comment: "")
      }

      /// en translation: Mark:
      ///
      /// Locales: en, hr
      static func site_mark(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_mark", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_mark"
        }

        return NSLocalizedString("site_mark", bundle: bundle, comment: "")
      }

      /// en translation: Missing Fields
      ///
      /// Locales: en, hr
      static func missing_data_alert_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("missing_data_alert_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "missing_data_alert_title"
        }

        return NSLocalizedString("missing_data_alert_title", bundle: bundle, comment: "")
      }

      /// en translation: My Location
      ///
      /// Locales: en, hr
      static func my_location(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("my_location", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "my_location"
        }

        return NSLocalizedString("my_location", bundle: bundle, comment: "")
      }

      /// en translation: My info
      ///
      /// Locales: en, hr
      static func my_info(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("my_info", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "my_info"
        }

        return NSLocalizedString("my_info", bundle: bundle, comment: "")
      }

      /// en translation: Name
      ///
      /// Locales: en, hr
      static func scope_name(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_name", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_name"
        }

        return NSLocalizedString("scope_name", bundle: bundle, comment: "")
      }

      /// en translation: Name:
      ///
      /// Locales: en, hr
      static func site_name(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_name", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_name"
        }

        return NSLocalizedString("site_name", bundle: bundle, comment: "")
      }

      /// en translation: Name:
      ///
      /// Locales: en, hr
      static func user_name(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("user_name", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "user_name"
        }

        return NSLocalizedString("user_name", bundle: bundle, comment: "")
      }

      /// en translation: No data available.
      ///
      /// Locales: en, hr
      static func no_data_available(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("no_data_available", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "no_data_available"
        }

        return NSLocalizedString("no_data_available", bundle: bundle, comment: "")
      }

      /// en translation: No internet connection.
      ///
      /// Locales: en, hr
      static func no_internet_connection(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("no_internet_connection", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "no_internet_connection"
        }

        return NSLocalizedString("no_internet_connection", bundle: bundle, comment: "")
      }

      /// en translation: Not completed
      ///
      /// Locales: en, hr
      static func not_completed(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("not_completed", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "not_completed"
        }

        return NSLocalizedString("not_completed", bundle: bundle, comment: "")
      }

      /// en translation: OK
      ///
      /// Locales: en, hr
      static func alert_ok_action(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("alert_ok_action", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "alert_ok_action"
        }

        return NSLocalizedString("alert_ok_action", bundle: bundle, comment: "")
      }

      /// en translation: Opening time:
      ///
      /// Locales: en, hr
      static func task_opening_time(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_opening_time", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_opening_time"
        }

        return NSLocalizedString("task_opening_time", bundle: bundle, comment: "")
      }

      /// en translation: Password
      ///
      /// Locales: en, hr
      static func password(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("password", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "password"
        }

        return NSLocalizedString("password", bundle: bundle, comment: "")
      }

      /// en translation: Please allow the app to use your location for all features to work.
      ///
      /// Locales: en, hr
      static func location_denied_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_denied_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_denied_alert_message"
        }

        return NSLocalizedString("location_denied_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: Please enter your username and password.
      ///
      /// Locales: en, hr
      static func missing_data_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("missing_data_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "missing_data_alert_message"
        }

        return NSLocalizedString("missing_data_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: Please turn on your location for all features to work.
      ///
      /// Locales: en, hr
      static func location_off_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_off_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_off_alert_message"
        }

        return NSLocalizedString("location_off_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: Power supply:
      ///
      /// Locales: en, hr
      static func site_power(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_power", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_power"
        }

        return NSLocalizedString("site_power", bundle: bundle, comment: "")
      }

      /// en translation: Search sites
      ///
      /// Locales: en, hr
      static func search_sites_placeholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("search_sites_placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "search_sites_placeholder"
        }

        return NSLocalizedString("search_sites_placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Site details
      ///
      /// Locales: en, hr
      static func site_details(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_details", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_details"
        }

        return NSLocalizedString("site_details", bundle: bundle, comment: "")
      }

      /// en translation: Sites
      ///
      /// Locales: en, hr
      static func sites(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("sites", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "sites"
        }

        return NSLocalizedString("sites", bundle: bundle, comment: "")
      }

      /// en translation: Sort
      ///
      /// Locales: en, hr
      static func sort(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("sort", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "sort"
        }

        return NSLocalizedString("sort", bundle: bundle, comment: "")
      }

      /// en translation: Status:
      ///
      /// Locales: en, hr
      static func task_status(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_status", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_status"
        }

        return NSLocalizedString("task_status", bundle: bundle, comment: "")
      }

      /// en translation: Task
      ///
      /// Locales: en, hr
      static func scope_task(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_task", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_task"
        }

        return NSLocalizedString("scope_task", bundle: bundle, comment: "")
      }

      /// en translation: Task details
      ///
      /// Locales: en, hr
      static func task_details(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_details", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_details"
        }

        return NSLocalizedString("task_details", bundle: bundle, comment: "")
      }

      /// en translation: Tasks
      ///
      /// Locales: en, hr
      static func tasks(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("tasks", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "tasks"
        }

        return NSLocalizedString("tasks", bundle: bundle, comment: "")
      }

      /// en translation: Tech
      ///
      /// Locales: en, hr
      static func scope_tech(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("scope_tech", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "scope_tech"
        }

        return NSLocalizedString("scope_tech", bundle: bundle, comment: "")
      }

      /// en translation: Technology:
      ///
      /// Locales: en, hr
      static func site_tech(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_tech", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_tech"
        }

        return NSLocalizedString("site_tech", bundle: bundle, comment: "")
      }

      /// en translation: The app is not authorized to use location services.
      ///
      /// Locales: en, hr
      static func location_restricted_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("location_restricted_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "location_restricted_alert_message"
        }

        return NSLocalizedString("location_restricted_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: The dequeued cell is not an instance of %s.
      ///
      /// Locales: en, hr
      static func cell_error(_ value1: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("cell_error", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "cell_error"
        }

        let format = NSLocalizedString("cell_error", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: The username or password is incorrect.
      ///
      /// Locales: en, hr
      static func failed_login_alert_message(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("failed_login_alert_message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "failed_login_alert_message"
        }

        return NSLocalizedString("failed_login_alert_message", bundle: bundle, comment: "")
      }

      /// en translation: User
      ///
      /// Locales: en, hr
      static func user(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("user", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "user"
        }

        return NSLocalizedString("user", bundle: bundle, comment: "")
      }

      /// en translation: Username
      ///
      /// Locales: en, hr
      static func username(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("username", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "username"
        }

        return NSLocalizedString("username", bundle: bundle, comment: "")
      }

      /// en translation: Username:
      ///
      /// Locales: en, hr
      static func user_username(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("user_username", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "user_username"
        }

        return NSLocalizedString("user_username", bundle: bundle, comment: "")
      }

      /// en translation: Users
      ///
      /// Locales: en, hr
      static func users(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("users", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "users"
        }

        return NSLocalizedString("users", bundle: bundle, comment: "")
      }

      /// en translation: action_id=update_task_status&task_id=%d&recorded=%s
      ///
      /// Locales: en, hr
      static func update_task_status(_ value1: Int, _ value2: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("update_task_status", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "update_task_status"
        }

        let format = NSLocalizedString("update_task_status", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// en translation: action_id=update_user_location&user_id=%d&lat=%f&lng=%f&recorded=%s
      ///
      /// Locales: en, hr
      static func update_user_location(_ value1: Int, _ value2: Double, _ value3: Double, _ value4: UnsafePointer<CChar>, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("update_user_location", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2, value3, value4)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "update_user_location"
        }

        let format = NSLocalizedString("update_user_location", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2, value3, value4)
      }

      /// en translation: locations
      ///
      /// Locales: en, hr
      static func notification_info(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("notification_info", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "notification_info"
        }

        return NSLocalizedString("notification_info", bundle: bundle, comment: "")
      }

      /// en translation: loggedUser
      ///
      /// Locales: en, hr
      static func logged_user_key(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("logged_user_key", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "logged_user_key"
        }

        return NSLocalizedString("logged_user_key", bundle: bundle, comment: "")
      }

      /// en translation: siteSort
      ///
      /// Locales: en, hr
      static func site_sort_key(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("site_sort_key", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "site_sort_key"
        }

        return NSLocalizedString("site_sort_key", bundle: bundle, comment: "")
      }

      /// en translation: taskSort
      ///
      /// Locales: en, hr
      static func task_sort_key(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("task_sort_key", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "task_sort_key"
        }

        return NSLocalizedString("task_sort_key", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
